name: Full-Stack CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # =====================
  # BACKEND JOB
  # =====================
  backend:
    name: Backend Build + Test + Security
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: |
          cd server
          npm install

      - name: Run Tests
        run: |
          cd server
          npm test --silent || echo "No tests found"

      - name: Security Check
        run: |
          cd server
          npm audit || true

  # =====================
  # FRONTEND JOB
  # =====================
  frontend:
    name: React Build Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: |
          cd client
          npm install

      - name: Build React App
        run: |
          cd client
          npm run build
